### ISSUE TITLE
Enable appveyor CI

### ISSUE THREAD

**Issue by epage** [crate-ci/example-base#1]
At the moment, I'm not seeing how to get the `crate-ci` org to show up in appveyor, so I can't add it.

**Comment by CAD97** [comment]
It should be enableable at this link: https://github.com/settings/connections/applications/01881570529737c25f97 (should go to your personal settings for the "AppVeyor CI" connection.

I've also requested it to have access to the crate-ci organization, so you should have an email about it.

**Comment by epage** [comment]
Got it working, thanks!
